version: "3.8"
services:
  node:
    build:
      dockerfile: ./Containerfile
      context: .
  nginx:
    restart: always
    image: nginx:1-alpine
    ports:
      - 4443:443
    volumes:
      - ./nginx/wss-proxy:/etc/nginx/conf.d/default.conf
      - ./nginx/selfsigned.crt:/etc/ssl/certs/selfsigned.crt
      - ./nginx/selfsigned.key:/etc/ssl/private/selfsigned.key
    depends_on:
      - node